import filecmp
import subprocess
import sys
from pathlib import Path

import pandas as pd
import pytest

from riskkit import report as rp
from riskkit.cli import main
from riskkit.positions import Book
from riskkit.synth import demo_book, demo_history, load_demo, write_demo

REPO = Path(__file__).resolve().parents[1]
DATA = REPO / "data/demo"


def test_demo_regenerates_byte_identically(tmp_path):
    """`riskkit demo` writes the same bytes twice, and the same bytes as the committed data/demo."""
    a, b = tmp_path / "a", tmp_path / "b"
    write_demo(a)
    main(["demo", "--out", str(b)])
    for name in ("book.json", "history.csv"):
        assert filecmp.cmp(a / name, b / name, shallow=False)
        assert filecmp.cmp(a / name, DATA / name, shallow=False), f"{name} differs from the committed demo"
    assert demo_history().equals(demo_history()) and demo_book() == demo_book()


def test_demo_history_has_clustering_and_negative_spot_vol_correlation():
    h = demo_history()
    r, dv = h["SYN:spot"], h["SYN:vol"]
    assert len(h) == 1259 and (h["SYN:vol_level"] > 0.05).all()
    assert (r**2).autocorr(1) > 0.05                       # volatility clustering
    assert r.autocorr(1) == pytest.approx(0.0, abs=0.08)    # but no return predictability
    assert r.corr(dv) < -0.2                                 # vol rises when spot falls
    assert abs(h["SYN:spot_level"].iloc[-1] - 500.0) < 1e-6


def test_report_states_units_confidence_horizon_and_n():
    book, mkt, hist = load_demo(DATA)
    rep = rp.build(book, mkt, hist, 0.975, 5, n_scenarios=2000, n_test=20, window=300, loss_limit=20_000.0)
    text = rp.render(rep)
    assert text.startswith("# riskkit report") and "\nstate: OK\n" in text
    assert "Units: US dollars" in text and "Confidence 98%" in text and "horizon 5 day(s)" in text
    assert "## VaR / ES, 5-day, 98%" in text and "| fhs-garch |" in text and "| 2000 |" in text
    assert "## Backtest, last 20 days" in text and "Kupiec p" in text and "Basel zone" in text
    assert "## Stress ladder" in text and "Oct-2008" in text and "## Reverse stress (loss limit $20,000)" in text
    assert "generated by `riskkit report`" in text
    for r in rep.results:
        assert f"| {r.method} |" in text


def test_report_empty_book_says_empty():
    _, mkt, hist = load_demo(DATA)
    text = rp.render(rp.build(Book.from_positions([]), mkt, hist, run_backtest=False))
    assert "\nstate: EMPTY\n" in text and "| — | 0 | 0 | 0 | EMPTY |" in text and "EMPTY [book]" in text


def test_report_prints_flags_under_a_lock():
    import math

    from riskkit.edge_cases import Lock
    book, mkt, hist = load_demo(DATA)
    lock = Lock("SYN", mkt.spot["SYN"], math.log(0.93), mkt.asof)
    text = rp.render(rp.build(book, mkt, hist, run_backtest=False, n_scenarios=500, lock=lock))
    assert "\nstate: LIMIT_DOWN\n" in text and "LIMIT_DOWN [SYN]" in text and "lock move continuing" in text


def test_report_under_a_lock_prints_the_governing_number_and_the_marked_spot():
    """The limit-down fixture of test_edge_cases: the raw 340-day window says VaR fell. The report's
    historical row must be the assessment's number (widened set, frozen at the last unlocked value if
    lower), so it is >= the last unlocked VaR / ES and above the raw recomputation; the header prints
    the last valid mid (500), not the locked print (465); the other methods run on the marked market;
    the governing number is printed by name."""
    import math

    from riskkit.edge_cases import Lock, assess
    from riskkit.positions import Market
    from riskkit.var import historical_var
    book, mkt, hist = load_demo(DATA)
    unlocked = assess(book, mkt, hist)
    window = pd.concat([hist.iloc[-300:], pd.DataFrame({"date": ["lock"] * 40, "SYN:spot": 0.0, "SYN:vol": 0.0})], ignore_index=True)
    raw = historical_var(book, mkt, window, 0.99, 1)
    assert raw.var < unlocked.var.var
    lock = Lock("SYN", mkt.spot["SYN"], math.log(0.93), mkt.asof - pd.Timedelta(minutes=30))
    locked_print = Market(mkt.asof, {"SYN": mkt.spot["SYN"] * 0.93}, mkt.vol)
    rep = rp.build(book, locked_print, window, run_backtest=False, n_scenarios=500, lock=lock, previous=unlocked.var)
    text = rp.render(rep)
    hist_row = next(r for r in rep.results if r.method == "historical")
    assert hist_row == rep.assessment.var and hist_row.var >= unlocked.var.var and hist_row.es >= unlocked.var.es
    assert hist_row.var > raw.var and hist_row.n_scenarios == len(window) + 3
    assert rep.market.spot["SYN"] == 500.0 and "SYN spot 500.00" in text and "465.00" not in text
    assert f"| historical | {hist_row.var:,.0f} | {hist_row.es:,.0f} | {hist_row.n_scenarios} |" in text
    assert f"Governing number (state LIMIT_DOWN): historical VaR {hist_row.var:,.0f} / ES {hist_row.es:,.0f}" in text
    assert all(m.spot == 500.0 for m in rep.assessment.marks)
    ok = rp.render(rp.build(book, mkt, hist, run_backtest=False, n_scenarios=500))
    assert "Governing number (state OK): historical VaR 6,277 / ES 9,002." in ok


def test_cli_report_runs(capsys):
    main(["report", "--data", str(DATA), "--scenarios", "500", "--n-test", "10", "--window", "300"])
    out = capsys.readouterr().out
    assert "state: OK" in out and "## Backtest, last 10 days" in out


def test_cli_report_seed_moves_only_the_simulated_lines(capsys):
    """`--seed` changes the Monte Carlo and FHS rows (and the simulated p-values); the historical and
    parametric rows are identical across seeds."""
    rows = {}
    for seed in ("0", "1"):
        main(["report", "--data", str(DATA), "--scenarios", "500", "--no-backtest", "--seed", seed])
        out = capsys.readouterr().out
        rows[seed] = {line.split("|")[1].strip(): line for line in out.splitlines() if line.startswith("| ")}
    for m in ("historical", "parametric-delta-gamma-vega"):
        assert rows["0"][m] == rows["1"][m]
    assert rows["0"]["monte-carlo"] != rows["1"]["monte-carlo"] and rows["0"]["fhs-garch"] != rows["1"]["fhs-garch"]


def test_cli_entry_point_help():
    r = subprocess.run([sys.executable, "-m", "riskkit.cli", "--help"], capture_output=True, text=True, check=True)
    assert "demo" in r.stdout and "report" in r.stdout
    assert isinstance(pd.DataFrame(), pd.DataFrame)
